# Generated by Django 4.2.6 on 2023-12-05 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=30, verbose_name="Car's name")),
                ('year', models.DateField(verbose_name='Year of issue')),
                ('color', models.CharField(default='None', max_length=30, verbose_name="Car's color")),
                ('vin_number', models.CharField(default='None', max_length=17, verbose_name="Car's vim")),
            ],
            options={
                'verbose_name': "Client's car",
                'verbose_name_plural': "Client's cars",
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last name')),
                ('middle_name', models.CharField(max_length=30, null=True, verbose_name='Middle name')),
                ('date_of_birth', models.DateField(verbose_name='Date of birth')),
            ],
            options={
                'verbose_name': 'Client information',
                'verbose_name_plural': 'Client information',
            },
        ),
        migrations.CreateModel(
            name='ListOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(verbose_name="Work's name")),
                ('price', models.FloatField(verbose_name='Price')),
            ],
            options={
                'verbose_name': 'List of work',
                'verbose_name_plural': 'List of work',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last name')),
                ('middle_name', models.CharField(max_length=30, null=True, verbose_name='Middle name')),
                ('job_title', models.CharField(verbose_name='Job title')),
                ('date_of_birth', models.DateField(verbose_name='Date of birth')),
            ],
            options={
                'verbose_name': 'Worker information',
                'verbose_name_plural': 'Worker information',
            },
        ),
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Date')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.car')),
                ('list_of_work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.listofwork')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.worker')),
            ],
            options={
                'verbose_name': 'Order List',
                'verbose_name_plural': 'Order list',
            },
        ),
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client'),
        ),
    ]
